# Generated by Django 4.0.4 on 2022-05-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='имя формы')),
            ],
            options={
                'verbose_name': 'данный',
                'verbose_name_plural': 'данные',
            },
        ),
        migrations.CreateModel(
            name='Types_of_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('title', models.CharField(max_length=30, verbose_name='название')),
            ],
            options={
                'verbose_name': 'типы полей',
                'verbose_name_plural': 'тип поля',
            },
        ),
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='название поли')),
                ('type_of_input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.types_of_input', verbose_name='тип поля')),
            ],
            options={
                'verbose_name': 'Поля',
                'verbose_name_plural': 'Поле',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='название формы')),
                ('inputs', models.ManyToManyField(to='core.inputs', verbose_name='поля')),
            ],
            options={
                'verbose_name': 'форма',
                'verbose_name_plural': 'формы',
            },
        ),
        migrations.CreateModel(
            name='DetailDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('item', models.TextField(verbose_name='запись')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.datas', verbose_name='данный')),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inputs', verbose_name='тип поля')),
            ],
            options={
                'verbose_name': 'детальное данный',
                'verbose_name_plural': 'детальные данные',
            },
        ),
        migrations.AddField(
            model_name='datas',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.forms', verbose_name='форма'),
        ),
    ]
