# Generated by Django 4.0.4 on 2022-05-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsOfInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('title', models.TextField(verbose_name='значение')),
            ],
            options={
                'verbose_name': 'спискок',
                'verbose_name_plural': 'списки пунктов',
            },
        ),
        migrations.AddField(
            model_name='inputs',
            name='items',
            field=models.ManyToManyField(to='core.itemsofinputs', verbose_name='значении'),
        ),
    ]
