# Generated by Django 4.0.4 on 2022-05-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemsofinputs_inputs_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputs',
            options={'verbose_name': 'поля', 'verbose_name_plural': 'поле'},
        ),
        migrations.AddField(
            model_name='datas',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='проверено'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='обязательность для заполнение'),
        ),
        migrations.AlterField(
            model_name='inputs',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.itemsofinputs', verbose_name='значении'),
        ),
    ]
