# Generated by Django 4.0.4 on 2022-05-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_inputs_options_datas_is_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildatas',
            name='item',
            field=models.TextField(null=True, verbose_name='запись'),
        ),
    ]
