# Generated by Django 4.0.4 on 2022-05-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_detaildatas_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовать'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forms', verbose_name='форма'),
        ),
    ]
