# Generated by Django 4.0.4 on 2022-05-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_forms_is_published_alter_datas_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildatas',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datas', verbose_name='данный'),
        ),
    ]
