# Generated by Django 4.0.4 on 2022-05-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_detaildatas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='types_of_input',
            name='is_selectable',
            field=models.BooleanField(default=False, verbose_name='выборычный тип'),
        ),
        migrations.AlterField(
            model_name='detaildatas',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inputs', verbose_name='тип поля'),
        ),
    ]
